- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: test
    url: http://172.31.32.113:8080
    user: admin
    password : admin123
    loop :
      - { item.repoName: "cart", item.componentName: "cart" }

